name: Publish
on:
  push:
    branches:
      - plugin/alternate
jobs:
  publish-coredns:
    name: Publish CoreDNS
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: tispace/coredns
          tags: |
            type=raw,value=v{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=latest
      # The v2 version of docker/build-push-action uses Docker Buildx to build.
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Image digest
        run:
          echo ${{ steps.docker_build.outputs.digest }}
